---
title: "R Notebook"
output: html_notebook
---


```{r}
library(simplextree)
library(dart)

## Apply random permutation to D 
set.seed(1234)
R <- dart::r_rips_complex(8, radius = 0.25, dim = 2)
if (R$dimension == 1 || R$n_simplices[3] <= 1){ next; }
D <- dart::boundary_matrix(R, labeled = TRUE, dims = 1:2)
p <- sample(seq(ncol(D$matrix[[1]])))
q <- sample(seq(ncol(D$matrix[[2]])))
D$matrix[[1]] <- D$matrix[[1]][,p,drop=FALSE]
D$matrix[[2]] <- D$matrix[[2]][p,q,drop=FALSE]
RV <- dart::reduce(D, options = c(clearing=TRUE), validate = TRUE)

Rl <- lapply(RV$R, function(m) as(m, "sparseMatrix"))
Vl <- lapply(RV$V, function(m) as(m, "sparseMatrix"))
move_idx <- combn(ncol(Rl[[1]]), 2)
move_idx <- move_idx[c(2,1),]
suppressWarnings({
  for (i in seq(ncol(move_idx))){
		rv <- move_left(R=Rl, V=Vl, i = move_idx[1,i], j = move_idx[2,i])
		r1_reduced <- dart::is_reduced(rv$R$R1)
		r2_reduced <- dart::is_reduced(rv$R$R2)
		if (!r1_reduced || !r2_reduced){
			print(i)
			stop("invalid")
		}
		Rl <- rv$R
		Vl <- rv$V
	} 
})


```
```{r debugging moves}
## Apply random permutation to D 
set.seed(1234)

use_R <- FALSE
R <- dart::r_rips_complex(10, radius = 0.35, dim = 2)
# R <- dart::r_rips_complex(10, radius = 0.25, dim = 2)

if (R$dimension == 1 || R$n_simplices[3] <= 1){ 
	stop("Too small")	
}
D <- dart::boundary_matrix(R, labeled = TRUE, dims = 1:2)
p <- sample(seq(ncol(D$matrix[[1]])))
q <- sample(seq(ncol(D$matrix[[2]])))
D$matrix[[1]] <- D$matrix[[1]][,p,drop=FALSE]
D$matrix[[2]] <- D$matrix[[2]][p,q,drop=FALSE]
RV <- dart::reduce(D, options = c(clearing=TRUE), validate = TRUE)

Rl <- lapply(RV$R, function(m) as(m, "sparseMatrix"))
Vl <- lapply(RV$V, function(m) as(m, "sparseMatrix"))
move_idx <- combn(ncol(Rl[[1]]), 2)
move_idx <- move_idx[c(2,1),]

coerce_field <- function(x){ x %% 2L }
is_tri <- function(v) { as.logical(Matrix::isTriangular(v)) }

suppressWarnings({
  for (cc in seq(ncol(move_idx))){
  	i <- move_idx[1,cc]
  	j <- move_idx[2,cc]
  	if (use_R){
  		if (i < j){
  			rv <- move_right(R=Rl, V=Vl, i=i, j=j)
  		} else {
  			rv <- move_left(R=Rl, V=Vl, i=i, j=j)
  		}
  	} else {
  		r1 <- psp_matrix(x=Rl[[1]])
			r2 <- psp_matrix(x=Rl[[2]])
			v1 <- psp_matrix(x=Vl[[1]])
			v2 <- psp_matrix(x=Vl[[2]])
			dart:::move_schedule_local(
				r1 = r1$matrix$as_XPtr(), v1 = v1$matrix$as_XPtr(), 
				r2 = r2$matrix$as_XPtr(), v2 = v2$matrix$as_XPtr(), 
				schedule = move_idx[,cc,drop=FALSE]-1L, 
				f = NULL
			)
			rv <- list(
				R=list(R1=r1$as.Matrix(), R2=r2$as.Matrix()), 
				V=list(V1=v1$as.Matrix(), V2=v2$as.Matrix())
			)
  	}
		r1_reduced <- dart::is_reduced(rv$R$R1)
		r2_reduced <- dart::is_reduced(rv$R$R2)
		v1_upt <- is_tri(as(rv$V$V1, "sparseMatrix"))
		v2_upt <- is_tri(as(rv$V$V2, "sparseMatrix"))
		
		D$matrix[[1]] <- permute_move(D$matrix[[1]], i, j, dims = "cols")
		D$matrix[[2]] <- permute_move(D$matrix[[2]], i, j, dims = "rows")
		
		R1 <- coerce_field(as(rv$R$R1, "sparseMatrix"))
		D1 <- coerce_field(as(D$matrix[[1]], "sparseMatrix"))
		V1 <- coerce_field(as(rv$V$V1, "sparseMatrix"))
		R2 <- coerce_field(as(rv$R$R2, "sparseMatrix"))
		D2 <- coerce_field(as(D$matrix[[2]], "sparseMatrix"))
		V2 <- coerce_field(as(rv$V$V2, "sparseMatrix"))
		diff1 <- coerce_field(R1-(D1%*%V1))
		diff2 <- coerce_field(R2-(D2%*%V2))
		
		if (!r1_reduced || !r2_reduced || !v1_upt || !v2_upt || !all(diff1 == 0) || !all(diff2 == 0)){
			print(cc)
			stop("invalid decomposition")
		}
		Rl <- rv$R
		Vl <- rv$V
	} 
})

# r1 <- psp_matrix(x=Rl$R1)
# r2 <- psp_matrix(x=Rl$R2)
# v1 <- psp_matrix(x=Vl$V1)
# v2 <- psp_matrix(x=Vl$V2)
# dart:::move_schedule_local(
# 	r1 = r1$matrix$as_XPtr(), v1 = v1$matrix$as_XPtr(), 
# 	r2 = r2$matrix$as_XPtr(), v2 = v2$matrix$as_XPtr(), 
# 	schedule = move_idx, 
# 	f = NULL
# )
# dart::is_reduced(r1$matrix$as.Matrix())
# 
# 
# is_upt <- is_tri(as(x$V, "sparseMatrix"))
# 
# coerce_field <- function(x){ x %% 2L }
# 
# R <- coerce_field(as(x$R, "sparseMatrix"))
# B <- coerce_field(as(D$matrix, "sparseMatrix"))
# V <- coerce_field(as(x$V, "sparseMatrix"))
# diff <- coerce_field(R-(B%*%V))
# is_dec <- all(diff == 0)
# dart::validate_decomp()
```

```{r}
library(dart)
x <- tdaunif::sample_circle(150, sd = 0.5)
fi <- rips_filtration(x, dim = 2)
D <- boundary_matrix(fi)
RV <- reduce(D, validate = FALSE, show_progress = TRUE)
```


```{r}
# 
# d1 <- as(D$matrix[[1]], "lgCMatrix")
# d2 <- as(D$matrix[[2]], "lgCMatrix")
# dv1 <- as(diag(ncol(d1)), "lgCMatrix")
# dv2 <- as(diag(ncol(d2)), "lgCMatrix")
# r1 <- RV$R[[1]]$as.Matrix()
# r2 <- RV$R[[2]]$as.Matrix()
# v1 <- as(RV$V[[1]], "sparseMatrix")
# v2 <- as(RV$V[[2]], "sparseMatrix")
# 
# d2[,4] <- xor(d2[,2], d2[,4])
# d2[,4] <- xor(d2[,3], d2[,4])
# d2[,4] <- xor(d2[,1], d2[,4])
# d2[,5] <- xor(d2[,3], d2[,5])
# d2[,6] <- xor(d2[,5], d2[,6])
# d2[,7] <- xor(d2[,6], d2[,7])
# 
# dv2[,4] <- xor(dv2[,2], dv2[,4])
# dv2[,4] <- xor(dv2[,3], dv2[,4])
# dv2[,4] <- xor(dv2[,1], dv2[,4])
# dv2[,5] <- xor(dv2[,3], dv2[,5])
# dv2[,6] <- xor(dv2[,5], dv2[,6])
# dv2[,7] <- xor(dv2[,6], dv2[,7])
# 
# 
# low_r2 <- apply(r2, 2, dart:::low_entry)
# low_r2 <- cbind(i = low_r2, j = seq(ncol(r2)))
# low_r2 <- low_r2[!apply(low_r2, 1, function(r) any(r == 0)),]
# v1[,low_r2[,1]] 
# r2[,low_r2[,2]]
# all(v1[,low_r2[,1]] == r2[,low_r2[,2]])
# 
# d1[,4] <- xor(d2[,2], d2[,4])
# 
# as((d2 %*% dv2) %% 2, "lgCMatrix")
# 
# r2 == as((d2 %*% v2) %% 2, "lgCMatrix")
# r1 == as((d1 %*% v1) %% 2, "lgCMatrix")

# dart::bipersistence()



low_entries <- apply(rv2$R$as.Matrix(), 2, dart:::low_entry)
names(low_entries) <- 1:ncol(rv2$R$as.Matrix())
i_col <- which(low_entries == 27)

R2p <- permute_move(R2, i = 27, j = 24, dims = "rows")
low_entries <- apply(R2p, 2, dart:::low_entry) 
nz_low_columns <- which(low_entries != 0)
nz_low_entries <- low_entries[nz_low_columns]
while(anyDuplicated(nz_low_entries)){
	dup_entry <- nz_low_entries[anyDuplicated(nz_low_entries)]
	which(nz_low_entries == dup_entry)
	
}
```

Sparse rips filtration # 1

```{r}
X <- tdaunif::sample_circle(50, sd = 0.10)
layout(matrix(1:4, ncol = 4))
r1 <- dart::sparse_rips_complex(X, epsilon = 0.0, dim = 2)
r2 <- dart::sparse_rips_complex(X, epsilon = 0.1, dim = 2)
r3 <- dart::sparse_rips_complex(X, epsilon = 0.2, dim = 2)
r4 <- dart::sparse_rips_complex(X, epsilon = 1.0, dim = 2)
plot(r1, coords = X, vertex_opt = list(cex=0.5), edge_opt = list(lwd=0.5), text_opt = list(labels=NA))
plot(r2, coords = X, vertex_opt = list(cex=0.5), edge_opt = list(lwd=0.5), text_opt = list(labels=NA))
plot(r3, coords = X, vertex_opt = list(cex=0.5), edge_opt = list(lwd=0.5), text_opt = list(labels=NA))
plot(r4, coords = X, vertex_opt = list(cex=0.5), edge_opt = list(lwd=0.5), text_opt = list(labels=NA))
```

```{r}
# ## Define the weighted radius
# radius <- function(i){
# 	r <- lambda_inorder[i]*(1+epsilon)/epsilon
# 	ifelse(alpha <= r, alpha, r)
# }
# simplex_birth_time <- function(simplex){
# 	if (length(simplex) == 1){ return(0.0) }
# 	r <- lambda_inorder[simplex]*((1+epsilon)^2)/epsilon
# 	ifelse(all(alpha <= r), min(r), Inf)
# }
# E <- as.vector(t(G$edges))
# e_births <- straverse(k_simplices(G, k = 1L), simplex_birth_time)
# sparse_e <- t(G$edges)[,e_births != Inf]
# 
# ## Make the sparse complex
# sparse_complex <- as.list(G$vertices) %>% 
# 	simplextree::simplex_tree() %>% 
# 	simplextree::insert(sparse_e) %>% 
# 	simplextree::expand(k=dim)

## Finally form the into a filtration
# bfs <- simplextree::level_order(sparse_complex)
# grades <- simplextree::straverse(bfs, simplex_birth_time)
# }

X <- tdaunif::sample_circle(1000, sd = 0.10)
plot(X)

sparse_fi <- sparse_rips(X, alpha = 0.30, epsilon = 0.5, dim = 2L)
plot(sparse_complex, coords = X)
```

Sparse rips filtration # 2
```{r}
X <- tdaunif::sample_circle(100, sd = 0.05)
plot(X, asp = 1, pch = 20)
points(X[p,], col = rainbow(length(p)))
p <- landmark::landmarks_maxmin(X, num = nrow(X))
d <- dist(X)
del_times <- c(max(d), sapply(seq_along(p)[-1], function(i){
	indices <- dart::rank_combn(rbind(p[i], p[1:(i-1)]), n = nrow(X))
	min(d[indices])
}))
w <- function(i, alpha, epsilon=1/3){
	tp <- del_times[match(i, p)]
	cc <- (1-2*epsilon)*tp
	if (alpha <= cc){ return(0) }
	if (cc < alpha && alpha < tp){ return(0.5*(alpha-cc)) }
	return(epsilon*alpha)
}
E0 <- simplextree::rips(d)$n_simplices[2]
ne <- sapply(del_times, function(eps) simplextree::rips(d, eps = eps)$n_simplices[2])

relaxed_rips <- function(d, ){
	
}
NER <- lapply(c(0.2, 0.4, 0.6, 0.8, 1.0)*(1/3), function(epsilon){
	ner <- sapply(del_times, function(alpha){
		d_alpha <- combn(nrow(X), 2, function(pq){
			w_p <- w(pq[1], alpha, epsilon=epsilon)
			w_q <- w(pq[2], alpha, epsilon=epsilon)
			d[dart::rank_combn(pq, n = nrow(X))] + w_p + w_q
		})
		simplextree::rips(d_alpha, eps = alpha)$n_simplices[2]
	})
	return(ner)
})

```

