---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dart)
set.seed(1234)
R <- pbgrad::r_geometric_complex(6, radius = 0.35, dim = 2, filtered = TRUE, coords = TRUE)
dx <- dist(attr(R, "coords"))
W <- dx[rankr::rank_comb(t(R$edges))]
FI <- new(dart:::ImplicitFiltration, R$as_XPtr(), W)

s0 <- unlist(simplex_to_str(FI$simplices[FI$simplex_dims == 0]))
s1 <- unlist(simplex_to_str(FI$simplices[FI$simplex_dims == 1]))
s2 <- unlist(simplex_to_str(FI$simplices[FI$simplex_dims == 2]))
b2 <- dart:::boundary_matrix_fi(FI$as_XPtr(), 2)
dimnames(b2) <- list(s1, s2)

b1 <- dart:::boundary_matrix_fi(FI$as_XPtr(), 1)
dimnames(b1) <- list(s0,s1)

ii2 <- simplex_to_str(t(kdtools::lex_sort(t(str_to_simplex(s1)))))

simplex_to_str(t(kdtools::lex_sort(t(str_to_simplex(s1)))))

i0 <- Matrix::invPerm(FI$shortlex_perm+1)[FI$simplex_dims == 0] - 1L
i1 <- Matrix::invPerm(FI$shortlex_perm+1)[FI$simplex_dims == 1] - 1L
i2 <- Matrix::invPerm(FI$shortlex_perm+1)[FI$simplex_dims == 2] - 1L


reindexed_rows <- i1[which(b2 != 0, arr.ind = TRUE)[,1]]-R$n_simplices[1]+1
reindexed_cols <- which(b2 != 0, arr.ind = TRUE)[,2]
Matrix::sparseMatrix(i=reindexed_rows, j = reindexed_cols, x = rep(1, length(reindexed_rows)))
dart::boundary_matrix(R$simplices, dim = 2)$matrix

pbgrad::boundary_matrix(R, 2)

set.seed(1234)
R <- pbgrad::r_geometric_complex(20, radius = 0.35, dim = 2, filtered = FALSE, coords = TRUE)
W <- runif(R$n_simplices[1])
FI <- new(dart:::ImplicitFiltration, R$as_XPtr(), W)

all(FI$grading[order(FI$grading)] == sort(FI$grading))

FI$simplex_ranks[FI$shortlex_perm+1L]
FI$simplex_ranks[FI$shortlex_perm[FI$simplex_dims == 1]+1L]

dart:::boundary_matrix_fi(FI$as_XPtr(), 1)


library(simplextree)
di <- sapply(as.list(simplextree::level_order(R)), length)-1L


all(dart:::inverse_permutation(a-1, x-1) == dart:::inverse_permutation2(x-1))

tail(FI$simplices, 5)
tail(R$simplices, 5)
# W <- straverse(level_order(R), function(simplex){
# 	if (length(simplex) <= 1){ return(0); }
# 	if (length(simplex) == 2){
# 		return(dx[rankr::rank_comb(matrix(simplex), n = R$n_simplices[1])])
# 	}
# 	return(max(dx[rankr::rank_comb(combn(simplex, 2), n = R$n_simplices[1])]))
# })

# c(4,6,8), n = 10
# r <- 91
# n <- 10
# d <- 3
# # 3, 5, 7
# s <- (combn(10,3)-1L)[,110] - 1L
# r <- 109
# n <- 10
# d <- 3

set.seed(1234)
x <- sample(seq(15)-1L)
setup_expr <- quote({ 
	set.seed(sample(1:100, size= 1))
	x <- sample(seq(250000)-1L) 
})
microbenchmark::microbenchmark({ dart:::inverse_permutation(x) }, times = 100L, setup = eval(setup_expr))
microbenchmark::microbenchmark({ dart:::inverse_permutation2(x) }, times = 100L, setup = eval(setup_expr))
# dart:::inverse_permutation(x)
# dart:::inverse_permutation2(x)

## Combinadic mapping 
# Original combinadic: http://math0.wvstateu.edu/~baker/cs405/code/Combinadics.html
# Dual index: https://planetcalc.com/8594/?license=1
unrank_cc <- function(r, k, n){
	N <- choose(n, k)
	ri <- (N-1L)-r
  s <- vector("integer", length = k)
  C <- lapply(seq(k), function(ki){ choose(0:n, k = ki) })
  for (i in seq(length(s), 1L)){
  	s[i] <- findInterval(x = ri, vec = C[[k]])-1L
  	ri <- ri - C[[k]][s[i]+1L]
  	k <- k - 1L
  }
  s <- (n-1L) - s
  return(rev(s))
}
sapply(seq(0, choose(10,3)-1L), function(r){ 
	unrank_cc(r, k = 3, n = 10) 
})+1



a <- seq(0, 100, by = 5)
dart:::test_binary_search(a, 51)

```



```{r}
set.seed(1234)
R <- pbgrad::r_geometric_complex(10, radius = 0.30, dim = 2, filtered = TRUE)
D <- dart::boundary_matrix(R$simplices, dim = c(1,2))
RV <- dart::reduce(D, output = "RV", validate = FALSE)
dart:::move_schedule_local(
	r1 = RV$R[[1]]$matrix$as_XPtr(), 
	v1 = RV$V[[1]]$matrix$as_XPtr(), 
	r2 = RV$R[[2]]$matrix$as_XPtr(), 
	v2 = RV$V[[2]]$matrix$as_XPtr(), 
	schedule = matrix(c(3, 8), nrow = 2)
)

```


```{r}
library(dart)
set.seed(1234)
R <- pbgrad::r_geometric_complex(20, radius = 0.20, dim = 2, filtered = TRUE, coords = TRUE)
K0 <- lapply(R$simplices, as.integer)
K1 <- lapply(unname(str_to_simplex(sample_filtration(unlist(simplex_to_str(K0))))), as.integer)
w0 <- R$weights
w1 <- sort(runif(sum(R$n_simplices), min = 0, max = max(R$weights)))
w1 <- w1[match(K0, K1)]

vineyards_schedule(K0,K1,w0,w1)

plot(rbind(cbind(0, w0), cbind(1,w1)), pch = 20)
for (i in seq_along(w0)){
	segments(x0 = 0, y0 = w0[i], x1 = 1, y1 = w1[i])
}


W0 <- impose_total_order(w0, eps = 20*sqrt(.Machine$double.eps))
W1 <- impose_total_order(w1, eps = 20*sqrt(.Machine$double.eps))
int_pairs <- dart:::SearchInStrip(W0, W1, 0, 1)
ncol(int_pairs)
kendall_dist(unlist(simplex_to_str(S0)), unlist(simplex_to_str(S1)))

impose_total_order2 <- function(v, eps = sqrt(.Machine$double.eps)){
	# cfactor <- seq(1, 2, length.out = length(w))*eps
	# f_diffs <- c(diff(cfactor),0)
	# noise <- cfactor + runif(n = length(w), min = f_diffs*(1/3), max = f_diffs*(2/3))
	# stopifnot(all(order(noise) == seq_along(noise)))
	#stopifnot(all(order(v0) == seq_along(v0)))
	
	ord_idx <- order(v)
	inv_idx <- Matrix::invPerm(ord_idx)
	noise <- rep(eps, length(v))*seq(1, length(v))
	return((v[ord_idx]+noise)[inv_idx])
}
W0 <- unname(impose_total_order2(w, eps = 1.0))
W1 <- unname(impose_total_order2(rev(w), eps = 1.0))

W0 <- impose_total_order2(w0, eps=0.01)
W1 <- impose_total_order2(w1, eps=0.01)

plot(rbind(cbind(0, W0), cbind(1,W1)), pch = 20)
for (i in seq_along(W0)){
	segments(x0 = 0, y0 = W0[i], x1 = 1, y1 = W1[i])
}

int_points <- dart:::span_intersections(int_pairs, w0, w1, 0, 1)
points(t(int_points), col = "red", pch = 21, cex = 0.5)


dart:::all_segment_intersections(rbind(0,w0,1,w1))
# kendall_dist(unlist(simplex_to_str(S0)), unlist(simplex_to_str(S1)))
```


