# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export PspBoolMatrix
NULL

reduce_pspbool <- function(D_ptr, V_ptr, show_progress = TRUE) {
    .Call(`_dart_reduce_pspbool`, D_ptr, V_ptr, show_progress)
}

reduce_local_pspbool <- function(D1_ptr, V1_ptr, D2_ptr, V2_ptr, clearing, show_progress = TRUE) {
    .Call(`_dart_reduce_local_pspbool`, D1_ptr, V1_ptr, D2_ptr, V2_ptr, clearing, show_progress)
}

simulate_vineyard_pspbool <- function(R_ptr, V_ptr, schedule, f = NULL, show_progress = TRUE) {
    .Call(`_dart_simulate_vineyard_pspbool`, R_ptr, V_ptr, schedule, f, show_progress)
}

move_schedule_local <- function(r1, v1, r2, v2, schedule, f = NULL) {
    .Call(`_dart_move_schedule_local`, r1, v1, r2, v2, schedule, f)
}

reduce_arma <- function(D, v, show_progress = TRUE) {
    .Call(`_dart_reduce_arma`, D, v, show_progress)
}

reduce_local_arma <- function(D1, v1, D2, v2, clearing, show_progress = TRUE) {
    .Call(`_dart_reduce_local_arma`, D1, v1, D2, v2, clearing, show_progress)
}

push_map <- function(x, m, b) {
    .Call(`_dart_push_map`, x, m, b)
}

boundary_matrix_fi_full <- function(filtration) {
    .Call(`_dart_boundary_matrix_fi_full`, filtration)
}

boundary_matrix_fi <- function(filtration, k) {
    .Call(`_dart_boundary_matrix_fi`, filtration, k)
}

boundary_matrix_st_full <- function(stree_ptr) {
    .Call(`_dart_boundary_matrix_st_full`, stree_ptr)
}

boundary_matrix_st <- function(stree, k) {
    .Call(`_dart_boundary_matrix_st`, stree, k)
}

all_lcs <- function(a, b) {
    .Call(`_dart_all_lcs`, a, b)
}

LIS <- function(a) {
    .Call(`_dart_LIS`, a)
}

countNumLIS <- function(x) {
    .Call(`_dart_countNumLIS`, x)
}

inversions <- function(a) {
    .Call(`_dart_inversions`, a)
}

inversion_count <- function(iv) {
    .Call(`_dart_inversion_count`, iv)
}

unique_numeric <- function(x, eps) {
    .Call(`_dart_unique_numeric`, x, eps)
}

longest_inc_subseq <- function(X) {
    .Call(`_dart_longest_inc_subseq`, X)
}

perm_dist_mat <- function(P, kendall = TRUE, normalize = FALSE) {
    .Call(`_dart_perm_dist_mat`, P, kendall, normalize)
}

fast_choose <- function(n, k) {
    .Call(`_dart_fast_choose`, n, k)
}

spearman_perm <- function(x, y) {
    .Call(`_dart_spearman_perm`, x, y)
}

rank_combn_rcpp <- function(C, n) {
    .Call(`_dart_rank_combn_rcpp`, C, n)
}

rank_combn_single_rcpp <- function(C, n) {
    .Call(`_dart_rank_combn_single_rcpp`, C, n)
}

unrank_combn_rcpp <- function(R, n, k) {
    .Call(`_dart_unrank_combn_rcpp`, R, n, k)
}

unrank_combn_single_rcpp <- function(rank, n, k) {
    .Call(`_dart_unrank_combn_single_rcpp`, rank, n, k)
}

simplex_to_str_rcpp <- function(x) {
    .Call(`_dart_simplex_to_str_rcpp`, x)
}

reduce_local_dense <- function(D1, v1, D2, v2, show_progress = TRUE) {
    .Call(`_dart_reduce_local_dense`, D1, v1, D2, v2, show_progress)
}

reduce_dense <- function(D, v, show_progress = TRUE) {
    .Call(`_dart_reduce_dense`, D, v, show_progress)
}

interval_cost_rcpp <- function(s, O) {
    .Call(`_dart_interval_cost_rcpp`, s, O)
}

pairwise_cost <- function(M) {
    .Call(`_dart_pairwise_cost`, M)
}

inverse_permutation <- function(p) {
    .Call(`_dart_inverse_permutation`, p)
}

inverse_permutation2 <- function(p) {
    .Call(`_dart_inverse_permutation2`, p)
}

test_unrank <- function(r, n, k) {
    .Call(`_dart_test_unrank`, r, n, k)
}

order_simplices <- function(simplices, weights) {
    .Call(`_dart_order_simplices`, simplices, weights)
}

pairwise_segment_intersections <- function(S, L, one_based = FALSE) {
    .Call(`_dart_pairwise_segment_intersections`, S, L, one_based)
}

all_segment_intersections <- function(S, one_based = FALSE) {
    .Call(`_dart_all_segment_intersections`, S, one_based)
}

bin_break <- function(x, bins) {
    .Call(`_dart_bin_break`, x, bins)
}

SearchInStrip <- function(y_b, y_e, b, e, one_based = FALSE) {
    .Call(`_dart_SearchInStrip`, y_b, y_e, b, e, one_based)
}

span_intersections <- function(indices, y_b, y_e, b, e, one_based = FALSE) {
    .Call(`_dart_span_intersections`, indices, y_b, y_e, b, e, one_based)
}

relative_transpositions <- function(n, T) {
    .Call(`_dart_relative_transpositions`, n, T)
}

bentley_ottmann <- function(S) {
    .Call(`_dart_bentley_ottmann`, S)
}

sparse_complex <- function(st_ptr, st_out, lambda, alpha, epsilon) {
    .Call(`_dart_sparse_complex`, st_ptr, st_out, lambda, alpha, epsilon)
}

