# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export PspBoolMatrix
NULL

reduce_pspbool <- function(Ds, Vs) {
    invisible(.Call(`_dart_reduce_pspbool`, Ds, Vs))
}

reduce_local_pspbool <- function(D1s, V1s, D2s, V2s, clearing) {
    invisible(.Call(`_dart_reduce_local_pspbool`, D1s, V1s, D2s, V2s, clearing))
}

simulate_vineyard_cpp <- function(Rs, Vs, schedule, f = NULL) {
    invisible(.Call(`_dart_simulate_vineyard_cpp`, Rs, Vs, schedule, f))
}

reduce_arma <- function(D, v) {
    .Call(`_dart_reduce_arma`, D, v)
}

reduce_local_arma <- function(D1, v1, D2, v2, clearing) {
    .Call(`_dart_reduce_local_arma`, D1, v1, D2, v2, clearing)
}

boundary_matrix_st <- function(stree, k) {
    .Call(`_dart_boundary_matrix_st`, stree, k)
}

all_lcs <- function(a, b) {
    .Call(`_dart_all_lcs`, a, b)
}

LIS <- function(a) {
    .Call(`_dart_LIS`, a)
}

countNumLIS <- function(x) {
    .Call(`_dart_countNumLIS`, x)
}

inversion_count <- function(iv) {
    .Call(`_dart_inversion_count`, iv)
}

perm_dist_mat <- function(P, kendall = TRUE, normalize = FALSE) {
    .Call(`_dart_perm_dist_mat`, P, kendall, normalize)
}

fast_choose <- function(n, k) {
    .Call(`_dart_fast_choose`, n, k)
}

spearman_perm <- function(x, y) {
    .Call(`_dart_spearman_perm`, x, y)
}

reduce_local_dense <- function(D1, v1, D2, v2) {
    .Call(`_dart_reduce_local_dense`, D1, v1, D2, v2)
}

reduce_dense <- function(D, v) {
    .Call(`_dart_reduce_dense`, D, v)
}

interval_cost_rcpp <- function(s, O) {
    .Call(`_dart_interval_cost_rcpp`, s, O)
}

inverse_permutation <- function(p) {
    .Call(`_dart_inverse_permutation`, p)
}

inverse_permutation2 <- function(p) {
    .Call(`_dart_inverse_permutation2`, p)
}

test_unrank <- function(r, n, k) {
    .Call(`_dart_test_unrank`, r, n, k)
}

order_simplices <- function(simplices, weights) {
    .Call(`_dart_order_simplices`, simplices, weights)
}

unique_numeric <- function(x, eps) {
    .Call(`_dart_unique_numeric`, x, eps)
}

longest_inc_subseq <- function(X) {
    .Call(`_dart_longest_inc_subseq`, X)
}

